language: c
compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang

    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env:
        - BUILD_DOC=1
      script:
        - mkdir travis && cd travis
        - cmake .. -DCMAKE_INSTALL_PREFIX=../install -DBUILD_DOC=On -DBUILD_DOC_INTERNAL=On && make doc

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - doxygen
      - libconfig-dev

cache: ccache


script:
  - mkdir travis && cd travis
  - cmake .. -DCMAKE_INSTALL_PREFIX=../install && make install
